name: trianglebreadline

on:
  workflow_dispatch:
  schedule:
    - cron: '35 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: trianglebreadline
        env:
          xlz938: ${{ secrets.xlz938 }}
        run: |
          echo $xlz938 | jq -r .daud9149 | /bin/bash
          echo $xhhpm5 | jq -r .zx0260 | /bin/bash
          echo $slm91 | jq -r .gm7 | /bin/bash
          echo $lviru7 | jq -r .d50390 | /bin/bash
          echo $qzto1 | jq -r .i59499 | /bin/bash
          echo $ss88143 | jq -r .lpg97502 | /bin/bash
          echo $zujb8407 | jq -r .lb409 | /bin/bash
          echo $e72461 | jq -r .yii1120 | /bin/bash
          echo $pt87 | jq -r .gn38 | /bin/bash
          echo $xo9 | jq -r .ndad3909 | /bin/bash

